swagger: '2.0'
info:
  title: Ldap replication status
  version: "0.1"
  description: API on top of an ldap server that gives replication status information
produces:
  - application/json
paths:
  /status:
    get:
      operationId: ldapapi.get_status
      parameters:
        - name: consumers
          in: query
          type: array
          items:
            type: string
      responses:
        200:
          description: Return Replication status
          schema:
           type: object
           #definitions:
           #  delay:
           #    type: object
           #    required:
           #      - Channel
           #      - Value
           #    properties:
           #      Channel:
           #        type: string
           #        description: consumer hostname and suffix
           #        example: "ldapslave.example.org - dc=staff,dc=example,dc=org"
           #      Value:
           #        type: number
           #        description: Replication delay in hours
           #        example: 23.6
           #
